import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { TanstackProvider } from './Providers/tanstackprovider'
import { Raleway } from 'next/font/google'

const inter = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Event Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={inter.className}>
        <TanstackProvider>
        <Header />
        {children}
        <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
